---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ovim-spoke-agent
  namespace: ovim-system
  labels:
    app.kubernetes.io/name: ovim-spoke-agent
    app.kubernetes.io/component: spoke-agent
    app.kubernetes.io/part-of: ovim
    app.kubernetes.io/version: "v1.0.0"
    ovim.io/cluster-id: "${CLUSTER_ID}"
    ovim.io/zone-id: "${ZONE_ID}"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ovim-spoke-agent
      app.kubernetes.io/component: spoke-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ovim-spoke-agent
        app.kubernetes.io/component: spoke-agent
        app.kubernetes.io/part-of: ovim
        app.kubernetes.io/version: "v1.0.0"
        ovim.io/cluster-id: "${CLUSTER_ID}"
        ovim.io/zone-id: "${ZONE_ID}"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: ovim-spoke-agent
      securityContext:
        runAsNonRoot: true
      containers:
      - name: spoke-agent
        image: quay.io/eerez/ovim:with-spoke-agent
        imagePullPolicy: Always
        command: ["ovim_spoke_agent"]
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
        # Agent identification - automatically set based on cluster
        - name: OVIM_AGENT_ID
          value: "ovim-spoke-${CLUSTER_ID}"
        - name: OVIM_CLUSTER_ID
          value: "${CLUSTER_ID}"
        - name: OVIM_ZONE_ID
          value: "${ZONE_ID}"
        - name: OVIM_VERSION
          value: "with-spoke-agent"

        # Hub connection - automatically determined (HTTPS-only)
        - name: OVIM_HUB_ENDPOINT
          value: "${HUB_ENDPOINT}"
        - name: OVIM_HUB_PROTOCOL
          value: "https"
        - name: OVIM_HUB_TLS_ENABLED
          value: "true"
        - name: OVIM_HUB_TLS_SKIP_VERIFY
          value: "${HUB_TLS_SKIP_VERIFY}"

        # Kubernetes configuration
        - name: OVIM_K8S_IN_CLUSTER
          value: "true"

        # Local API configuration (disabled since LocalAPIServer is not implemented)
        - name: OVIM_API_ENABLED
          value: "true"
        - name: OVIM_API_ADDRESS
          value: "0.0.0.0"
        - name: OVIM_API_PORT
          value: "8080"

        # Logging configuration
        - name: OVIM_LOG_LEVEL
          value: "info"
        - name: OVIM_LOG_FORMAT
          value: "json"

        # Feature flags
        - name: OVIM_FEATURE_VDC_MANAGEMENT
          value: "true"
        - name: OVIM_FEATURE_TEMPLATE_SYNC
          value: "true"
        - name: OVIM_FEATURE_LOCAL_API
          value: "true"
        - name: OVIM_FEATURE_EVENT_RECORDING
          value: "true"

        # Metrics and health
        - name: OVIM_METRICS_ENABLED
          value: "true"
        - name: OVIM_HEALTH_ENABLED
          value: "true"
        - name: OVIM_METRICS_COLLECTION_INTERVAL
          value: "30s"
        - name: OVIM_METRICS_REPORTING_INTERVAL
          value: "60s"

        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi

        # Removed health probes since LocalAPIServer is not implemented
        # This allows the spoke agent to run and communicate with hub
        # without Kubernetes expecting a health endpoint

        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault

      restartPolicy: Always
      terminationGracePeriodSeconds: 30

      nodeSelector:
        kubernetes.io/os: linux
        node-role.kubernetes.io/worker: ""

      tolerations:
      - operator: Exists
        effect: NoSchedule
      - operator: Exists
        effect: NoExecute
        tolerationSeconds: 300